# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/google/certificate-transparency-go
%global goipath         github.com/google/certificate-transparency-go
Version:                1.1.2

%gometa

%global common_description %{expand:
Auditing for TLS certificates (Go code).}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md AUTHORS README.md CHANGELOG.md\\\
                        CONTRIBUTORS trillian/README.md

Name:           trillian-certificate-transparency-server
Release:        1%{?dist}
Summary:        Auditing for TLS certificates (Go code)

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{name}.service

BuildRequires:  systemd-rpm-macros

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in trillian/ctfe/ct_server; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -m 0755 -vd                     %{buildroot}%{_unitdir}
install -m 0644 -vp %{SOURCE1}          %{buildroot}%{_unitdir}

%if %{with check}
%check
%gocheck
%endif

%post
%systemd_post %{name}.service

%preun
%systemd_preun %{name}.service

%postun
%systemd_postun %{name}.service

%files
%license LICENSE
%doc CONTRIBUTING.md AUTHORS README.md CHANGELOG.md CONTRIBUTORS
%doc trillian/README.md
%{_bindir}/*
%{_unitdir}/%{name}.service
%gopkgfiles

%changelog
* Tue Apr 26 2022 Ivan Font <ifont@redhat.com> - 1.1.2-1
- Initial package
