# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/sigstore/rekor
%global goipath         github.com/sigstore/%{name}
Version:                0.6.0

%gometa

%global common_description %{expand:
Software Supply Chain Transparency Log.}

%global golicenses      COPYRIGHT.txt LICENSE
%global godocs          OWNERS.md DEPRECATIONS.md CODE_OF_CONDUCT.md types.md\\\
                        FEATURES.md README.md CONTRIBUTORS.md CHANGELOG.md\\\
                        MAINTAINERS.md pkg/types/README.md\\\
                        pkg/types/intoto/README.md pkg/types/alpine/README.md\\\
                        pkg/pki/ssh/README.md release/README.md

Name:           rekor
Release:        1%{?dist}
Summary:        Software Supply Chain Transparency Log

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYRIGHT.txt LICENSE
%doc OWNERS.md DEPRECATIONS.md CODE_OF_CONDUCT.md types.md FEATURES.md README.md
%doc CONTRIBUTORS.md CHANGELOG.md MAINTAINERS.md pkg/types/README.md
%doc pkg/types/intoto/README.md pkg/types/alpine/README.md pkg/pki/ssh/README.md
%doc release/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Apr 26 2022 Ivan Font <ifont@redhat.com> - 0.6.0-1
- Initial package
