# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/google/trillian
%global goipath         github.com/google/trillian
Version:                1.4.0

%gometa

%global common_description %{expand:
A transparent, highly scalable and cryptographically verifiable data store.}

%global golicenses      LICENSE
%global godocs          docs examples CONTRIBUTING.md AUTHORS README.md\\\
                        CHANGELOG.md CONTRIBUTORS PULL_REQUEST_TEMPLATE.md\\\
                        extension/README.md integration/README.md\\\
                        experimental/batchmap/README.md quota/etcd/README.md\\\
                        deployment/README.md storage/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A transparent, highly scalable and cryptographically verifiable data store

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in docs/storage/commit_log storage/tools/dump_tree quota/redis/redistb storage/tools/hasher docs/merkletree/treetex testonly/mdm/mdmtest; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs examples CONTRIBUTING.md AUTHORS README.md CHANGELOG.md CONTRIBUTORS
%doc PULL_REQUEST_TEMPLATE.md extension/README.md integration/README.md
%doc experimental/batchmap/README.md quota/etcd/README.md deployment/README.md
%doc storage/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Apr 18 2022 Ivan Font <ifont@redhat.com> - 1.4.0-1
- Initial package
